#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
.SYNOPSIS
  One-click installer for Waybill Tracking on Windows (PowerShell 7+ / pwsh).
.DESCRIPTION
  Checks prerequisites, clones/updates the repo, generates JWT secret, and
  starts all services via Docker Compose.
#>

$Host.UI.RawUI.ForegroundColor = $null  # reset

$InfoColor  = 'Cyan'
$OkColor    = 'Green'
$WarnColor  = 'Yellow'
$ErrColor   = 'Red'

function info  { Write-Host "[INFO]  $args" -ForegroundColor $InfoColor }
function ok    { Write-Host "[OK]    $args" -ForegroundColor $OkColor }
function warn  { Write-Host "[WARN]  $args" -ForegroundColor $WarnColor }
function err   { Write-Host "[ERR]   $args" -ForegroundColor $ErrColor; exit 1 }

$RepoUrl     = 'https://github.com/akiromishidoze/waybill-tracking.git'
$InstallDir  = if ($env:INSTALL_DIR) { $env:INSTALL_DIR } else { Join-Path $HOME 'waybill-tracking' }

info '--- Waybill Tracking Installer ---'
Write-Host

# --- Prerequisites ---
$missing = @()
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { $missing += 'Docker' }
if (-not (Get-Command git    -ErrorAction SilentlyContinue)) { $missing += 'Git'  }
$dcCmd = if (Get-Command 'docker compose' -ErrorAction SilentlyContinue) { 'docker compose' }
         elseif (Get-Command docker-compose -ErrorAction SilentlyContinue) { 'docker-compose' }
         else { $missing += 'Docker Compose plugin' }
if ($missing.Count) { err "Missing: $($missing -join ', '). Install Docker Desktop and Git for Windows." }

ok 'Prerequisites met: Docker, Git, Docker Compose'

# --- Clone / update ---
if (Test-Path (Join-Path $InstallDir '.git')) {
  warn "Directory $InstallDir already contains a git repo."
  $yn = Read-Host '  Use existing repo and pull latest? [Y/n]'
  if ($yn -notin 'n','N','no','No') {
    Push-Location $InstallDir
    git pull --ff-only
    Pop-Location
    ok 'Pulled latest.'
  } else {
    info 'Using existing repo as-is.'
  }
} else {
  info "Cloning into $InstallDir ..."
  git clone $RepoUrl $InstallDir
  ok 'Repository cloned.'
}

Push-Location $InstallDir

# --- Generate JWT secret ---
$jwtBytes = New-Object byte[] 48
[System.Security.Cryptography.RandomNumberGenerator]::Fill($jwtBytes)
$jwtSecret = [System.Convert]::ToBase64String($jwtBytes)

$envContent = @"
# Generated by install.ps1 on $(Get-Date -Format 'o')
JWT_SECRET=$jwtSecret
"@

$envFile = Join-Path $InstallDir '.env'
if (Test-Path $envFile) {
  warn '.env file already exists — backing up to .env.bak'
  Copy-Item $envFile "$envFile.bak" -Force
}
Set-Content -Path $envFile -Value $envContent -NoNewline
ok 'JWT_SECRET generated and written to .env'

# --- Docker Compose ---
info 'Pulling images and building services ...'
Invoke-Expression "$dcCmd pull --quiet 2>`$null"
Invoke-Expression "$dcCmd build --quiet 2>`$null"

info 'Starting all services in detached mode ...'
Invoke-Expression "$dcCmd up -d"

info 'Waiting for services to become healthy ...'
$maxRetries = 30
$healthy = $false
for ($i = 0; $i -lt $maxRetries; $i++) {
  Start-Sleep -Seconds 3
  $healthy = $true
  foreach ($svc in @('postgres','core-api','analytics-api','dashboard')) {
    $status = & $dcCmd ps --format json $svc 2>$null | ForEach-Object {
      try { ($_ | ConvertFrom-Json).Health } catch { '' }
    }
    if (-not ($status -match 'healthy|running|Up')) { $healthy = $false; break }
  }
  if ($healthy) { break }
}
if (-not $healthy) { warn 'Some services may still be starting (timeout).' }

Write-Host
info '=== Setup Complete ==='
Write-Host
Write-Host "  Dashboard      http://localhost:5173"    -ForegroundColor Cyan
Write-Host "  Core API       http://localhost:8080/health" -ForegroundColor Cyan
Write-Host "  Analytics API  http://localhost:8000/health" -ForegroundColor Cyan
Write-Host "  Postgres       localhost:5432 (user: postgres, password: postgres)" -ForegroundColor Cyan
Write-Host "  Redis          localhost:6379"           -ForegroundColor Cyan
Write-Host "  Elasticsearch  http://localhost:9200"    -ForegroundColor Cyan
Write-Host "  Prometheus     http://localhost:9090"    -ForegroundColor Cyan
Write-Host "  Grafana        http://localhost:3001 (admin / admin)" -ForegroundColor Cyan
Write-Host
ok 'Waybill Tracking is running!'
Write-Host
Write-Host "Run  cd $InstallDir; $dcCmd logs -f  to follow logs."
Write-Host "Run  $dcCmd down  to stop all services."

Pop-Location
